name: Update Tap

on:
  repository_dispatch:
    types: [update-formula]

jobs:
  update-formula:
    runs-on: ubuntu-latest
    steps:
      - name: Debug payload  
        run: |
          echo "Event type: ${{ github.event.action }}"
          echo "Version: ${{ github.event.client_payload.version }}"
          echo "Release URL: ${{ github.event.client_payload.release_url }}"

      - name: Checkout tap repository
        uses: actions/checkout@v4
        with:
          repository: bixu/homebrew-apiary
          token: ${{ secrets.HOMEBREW_TAP_TOKEN }}
          path: homebrew-tap

      - name: Get release assets
        id: get-assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Use version from client payload
          version="${{ github.event.client_payload.version }}"

          # Get the release data from the provided release URL
          release_data=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "${{ github.event.client_payload.release_url }}")

          # Extract download URLs for the archives
          arm_url=$(echo "$release_data" | jq -r '.assets[] | select(.name | contains("aarch64-apple-darwin.tar.gz")) | .browser_download_url')
          
          # Download and calculate SHA256 for both archives
          curl -L "$arm_url" -o arm-archive.tar.gz

          arm_sha256=$(sha256sum arm-archive.tar.gz | cut -d' ' -f1)
          
          echo "version=$version" >> $GITHUB_OUTPUT
          echo "arm_sha256=$arm_sha256" >> $GITHUB_OUTPUT

      - name: Update formula
        run: |
          cd homebrew-tap

          # Update the formula with new version and SHA256 values
          sed -i "s/version '[^']*'/version '${{ steps.get-assets.outputs.version }}'/" Formula/apiary.rb
          sed -i "s/sha256 'PLACEHOLDER_ARM_SHA256'/sha256 '${{ steps.get-assets.outputs.arm_sha256 }}'/" Formula/apiary.rb

      - name: Commit and push changes
        run: |
          cd homebrew-tap
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Formula/apiary.rb
          git commit -m "Update apiary to version ${{ steps.get-assets.outputs.version }}"
          git push
